@startuml libGDX component context
!include <C4/C4_Container>

SHOW_PERSON_OUTLINE()

title System Component Model

Person(contributers, "Contributer", "Community contributor of libGDX")
Person(game_developer, "Game Developer", "Persona that is building a game")

System_Boundary(libgdx, "libGDX") {
    Container(backends, "Backends")
    Container(extensions, "Extensions")
    Container(tests, "Tests")

    Boundary(gdx, "gdx") {
        Boundary(audio, "audio") {
            Container(AudioDevice, "AudioDevice", "Interface")
            Container(AudioRecorder, "AudioRecorder", "Interface")
            Container(Music, "Music", "Interface")
            Container(Sound, "Sound", "Interface")
        }
        Boundary(math, "math") {
            Boundary(collision, "collision") {
                Container(BoundingBox, "BoundingBox", "Class")
                Container(OrientedBoundingBox, "OrientedBoundingBox", "Class")
                Container(Ray, "Ray", "Class")
                Container(Segment, "Segment", "Class")
                Container(Sphere, "Sphere", "Class")
            }
            Container(Affine2, "Affine2", "Class")
            Container(BSpline, "BSpline", "Class")
            Container(Bezier, "Bezier", "Class")
            Container(Bresenham2, "Bresenham2", "Class")
            Container(CatmullRomSpline, "CatmullRomSpline", "Class")
            Container(Circle, "Circle", "Class")
            Container(ConvexHull, "ConvexHull", "Class")
            Container(CumulativeDistribution, "CumulativeDistribution", "Class")
            Container(DelauneyTriangulator, "DelauneyTriangulator", "Class")
            Container(EarClippingTriangulator, "EarClippingTriangulator", "Class")
            Container(Ellipse, "Ellipse", "Class")
            Container(FLoatCounter, "FloatCounter", "Class")
            Container(Frustum, "Frustum", "Class")
            Container(GeometryUtils, "GeometryUtils", "Class")
            Container(GridPoint2, "GridPoint2", "Class")
            Container(GridPoint3, "GridPoint3", "Class")
            Container(Interpolation, "Interpolation", "Class")
            Container(Intersector, "Intersector", "Class")
            Container(MathUtils, "MathUtils", "Class")
            Container(Matrix3, "Matrix3", "Class")
            Container(Matrix4, "Matrix4", "Class")
            Container(Octree, "Octree", "Class")
            Container(Path, "Path", "Interface")
            Container(Plane, "Plane", "Class")
            Container(Polygon, "Polygon", "Class")
            Container(Polyline, "Polyline", "Class")
            Container(Quaternion, "Quaternion", "Class")
            Container(RandomXS128, "RandomXS128", "Class")
            Container(Rectangle, "Rectangle", "Class")
            Container(Shape2D, "Shape2D", "Interface")
            Container(Vector, "Vector", "Interface")
            Container(Vector2, "Vector2", "Class")
            Container(Vector3, "Vector3", "Class")
            Container(Vector4, "Vector4", "Class")
            Container(WindowedMean, "WindowedMean", "Class")
        }
    }
}

System_Ext(libraries, "libraries", "External libraries and API's used in the project")

Rel(backends, libraries, "Uses")
Rel(tests, libraries, "Uses")

Rel(game_developer, backends, "Builds on", "Integration")
Rel(contributers, libgdx, "Develops")

Rel(gdx, math, "Includes")
Rel(gdx, audio, "Includes")

Rel(backends, gdx, "Uses")
Rel(extensions, gdx, "Uses")
Rel(tests, gdx, "Uses")

Rel(Vector2, Vector, "Implements")
Rel(Vector3, Vector, "Implements")
Rel(Vector4, Vector, "Implements")

Rel(BSpline, Path, "Implements")
Rel(Bezier, Path, "Implements")
Rel(CatmullRomSpline, Path, "Implements")

Rel(Shape2D, Circle, "Implemented by")
Rel(Shape2D, Ellipse, "Implemented by")
Rel(Shape2D, Polygon, "Implemented by")
Rel(Shape2D, Polyline, "Implemented by")
Rel(Shape2D, Rectangle, "Implemented by")

Rel(Matrix4, Affine2, "Uses")
Rel(Ellipse, Circle, "Uses")
Rel(Intersector, Circle, "Uses")
Rel(Rectangle, Circle, "Uses")
Rel(Intersector, Frustum, "Uses")
Rel(Octree, Frustum, "Uses")
Rel(DelauneyTriangulator, GeometryUtils, "Uses")
Rel(EarClippingTriangulator, GeometryUtils, "Uses")
Rel(Polygon, GeometryUtils, "Uses")
Rel(Bresenham2, GridPoint2, "Uses")
Rel(Vector, Interpolation, "Uses")
Rel(Vector2, Interpolation, "Uses")
Rel(Vector3, Interpolation, "Uses")
Rel(Vector4, Interpolation, "Uses")
Rel(Octree, Intersector, "Uses")
Rel(OrientedBoundingBox, Intersector, "Uses")
Rel(Affine2, MathUtils, "Uses")
Rel(BSpline, MathUtils, "Uses")
Rel(Bezier, MathUtils, "Uses")
Rel(CatmullRomSpline, MathUtils, "Uses")
Rel(Circle, MathUtils, "Uses")
Rel(CumulativeDistribution, MathUtils, "Uses")
Rel(Ellipse, MathUtils, "Uses")
Rel(GeometryUtils, MathUtils, "Uses")
Rel(Interpolation, MathUtils, "Uses")
Rel(Intersector, MathUtils, "Uses")
Rel(Matrix3, MathUtils, "Uses")
Rel(Matrix4, MathUtils, "Uses")
Rel(Polygon, MathUtils, "Uses")
Rel(Quaternion, MathUtils, "Uses")
Rel(Vector2, MathUtils, "Uses")
Rel(Vector3, MathUtils, "Uses")
Rel(Vector4, MathUtils, "Uses")
Rel(Affine2, Matrix3, "Uses")
Rel(Matrix4, Matrix3, "Uses")
Rel(Quaternion, Matrix3, "Uses")
Rel(Vector2, Matrix3, "Uses")
Rel(Vector3, Matrix3, "Uses")
Rel(Quaternion, Matrix4, "Uses")
Rel(Affine2, Matrix4, "Uses")
Rel(Intersector, Matrix4, "Uses")
Rel(Matrix3, Matrix4, "Uses")
Rel(Frustum, Plane, "Uses")
Rel(Intersector, Plane, "Uses")
Rel(Intersector, Polygon, "Uses")
Rel(Matrix4, Quaternion, "Uses")
Rel(MathUtils, RandomXS128, "Uses")
Rel(Intersector, Rectangle, "Uses")
Rel(Polygon, Rectangle, "Uses")
Rel(Bezier, Vector, "Uses")
Rel(Bresenham2, Vector, "Uses")
Rel(CatmullRomSpline, Vector, "Uses")
Rel(Affine2, Vector2, "Uses")
Rel(Circle, Vector2, "Uses")
Rel(DelauneyTriangulator, Vector2, "Uses")
Rel(Ellipse, Vector2, "Uses")
Rel(GeometryUtils, Vector2, "Uses")
Rel(Intersector, Vector2, "Uses")
Rel(Matrix3, Vector2, "Uses")
Rel(Polyline, Vector2, "Uses")
Rel(Rectangle, Vector2, "Uses")
Rel(Shape2D, Vector2, "Uses")
Rel(Vector4, Vector2, "Uses")
Rel(Vector3, Vector2, "Uses")
Rel(Frustum, Vector3, "Uses")
Rel(Intersector, Vector3, "Uses")
Rel(Matrix3, Vector3, "Uses")
Rel(Matrix4, Vector3, "Uses")
Rel(Octree, Vector3, "Uses")
Rel(Plane, Vector3, "Uses")
Rel(Quaternion, Vector3, "Uses")
Rel(Quaternion, Vector3, "Uses")
Rel(Vector4, Vector3, "Uses")
Rel(BoundingBox, Vector3, "Uses")
Rel(Ray, Vector3, "Uses")
Rel(Sphere, Vector3, "Uses")
Rel(Segment, Vector3, "Uses")

Rel(FLoatCounter, WindowedMean, "Uses")
Rel(Octree, BoundingBox, "Uses")
Rel(Intersector, BoundingBox, "Uses")
Rel(Frustum, OrientedBoundingBox, "Uses")
Rel(Intersector, OrientedBoundingBox, "Uses")
Rel(BoundingBox, OrientedBoundingBox, "Uses")
Rel(Intersector, Ray, "Uses")
Rel(Octree, Ray, "Uses")
Rel(Octree, Ray, "Uses")
@enduml